# help text, use command 'help command' will print '_help_text_/help_${command}'
# such as: '$> help' -> print '_help_text_/help_None'
_help_text_:
  help_None: |-
    ---------------------------------------------------------------------
    this is item help!

    init: add dirs like 'src', 'bin', 'include', add 'build' and so on.
    make: from src dir's file use gcc or else to build execable file.
    run : run the execable file.

    exit: exit the app_bot.
    quit: exit the qpp_bot.

    help: show this doc.
    ---------------------------------------------------------------------
  help_init: |-
    None
  help_exit: |-
    None
  help_quit: |-
    None
  help_help: |-
    None

# helper's config variable
_helper_:
  # helper's color:
  # (imp:important_part)(sec:secondary_part)(imp:'> ')
  # such as: (imp:'~\path\to\dir')(sec:'(under item)')(imp:'> ')
  _color_:
    important_color: '#ffaaaa'
    secondary_color: '#ffff88'

# when use command 'init lang' item will call '__init__/${lang}'
__init__:
  C:
    __new_dir__:
      - bin
      - build
      - doc
      - include
      - src
    __file__:
      - build/item_config.yaml
    __command__:
      - ['!git', init]
      - ['!git', add, '.']
    make:
      - ['!gcc', '${item_root}/src/${file_name}', -o, '${item_root}/bin/${file_name_without_suffix}']
    run:
      - ['!${item_root}/bin/${file_name}']

  cpp:
    __new_dir__:
      - bin
      - build
      - doc
      - include
      - src
    __file__:
      - build/item_config.yaml
    make:
      - ['!gcc', '${item_root}/src/${file_name}', -o, '${item_root}/bin/${file_name_without_suffix}']
    run:
      - ['!${item_root}/bin/${file_name}']

  python:
    make:
      - [] # do nothing
    run:
      - ['!python', '${item_root}/src/${file_name}']

  latex:
    make:
      - ['!xelatex', '${item_root}/src/${file_name}']
      - ['!xelatex', '${item_root}/src/${file_name}']
    run:
      - [] # do nothing